docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Intro: intro.md
    - Reference:
        - "The Module Manager": module-manager.md
        - "The Module Class": module-class.md
        - "The Module Autoloader": module-autoloader.md
        - "Best Practices when Creating Modules": best-practices.md
site_name: laminas-modulemanager
site_description: laminas-modulemanager
repo_url: 'https://github.com/laminas/laminas-modulemanager'

